services:
  redis:
    image: redis:7-alpine
    container_name: r8gate-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: r8gate-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  redis-data:
  mongo-data: